### ISSUE TITLE
How to get these working?

### ISSUE THREAD

**Issue by Ciantic** [intellifactory/websharper.ui.next.samples#24]
I created a project from VS template "UI.Next Single-Page Application" but the content is not react-like virtual dom example, it's something old I presume.

Next I emptied the module Client and copy pasted stuff from basicExample in docs. Now my Client.fs is like this

```
namespace FsharpTestSinglePageNext

open WebSharper
open WebSharper.JavaScript
open WebSharper.JQuery
open WebSharper.UI.Next
open WebSharper.UI.Next.Html
open WebSharper.UI.Next.Notation

[<JavaScript>]
module Client =    
  
    let Main =
        let rvContent = Var.Create ""
        let vUpperContent =
            rvContent.View
            |> View.Map (fun t -> t.ToUpper())

        Div [] [
            Doc.Input [] rvContent
            Label [] [Doc.TextView vUpperContent]
        ]
```

But it can't recongize `Var.Create` nor `rvContent.View`. I also tried to copy paste "canonical" Todo task list example, but with no luck with that either.

**Comment by qwe2** [comment]
That's an issue with `open WebSharper.UI.Next.Html` importing a tag named `Var` hiding the actual `Var`. This is pretty unfortunate, but until we fix the issue you can do something like `module H = WebSharper.UI.Next.Html` and use `H.Label` instead of `Label`.

**Comment by Tarmil** [comment]
I just [fixed the issue in the code](https://github.com/intellifactory/websharper.ui.next/commit/7691fba197003663d0f336bd58c900c35abce7e6), so it will be fixed in the next nuget release.

**Comment by Ciantic** [comment]
Is there any examples that work with "react-like" API? I can't get even a simple Div to render.

**Comment by granicz** [comment]
The samples repository, the one you are copy-pasting from, uses (non-standard) helpers such as `divc` from:

https://github.com/intellifactory/websharper.ui.next.samples/blob/master/src/Utilities.fs

..., among others.  I would recommend taking the entire repository for testing, with the caveat that it has not been converted to the final 3.X syntax (and addressed for namespace and other changes since the early 3.0 alpha that it's currently using.)  We will get to synching it up hopefully today.

**Comment by Ciantic** [comment]
Oh, right. How about the simples of simplest things:

```
// $begin{copyright}
//
// This file is confidential and proprietary.
//
// Copyright (c) IntelliFactory, 2004-2014.
//
// All rights reserved.  Reproduction or use in whole or in part is
// prohibited without the written consent of the copyright holder.
//-----------------------------------------------------------------
// $end{copyright}
namespace FsharpTestSinglePageNext

open WebSharper
open WebSharper.UI.Next
open WebSharper.UI.Next.Html

// A simple example consisting of a label which mirrors the content of a text
// box.
// See this live at http://intellifactory.github.io/websharper.ui.next/#SimpleTextBox.fs !

[<JavaScript>]
module Client =

    let Main () =
        // Put together our RDOM structures; some bootstrap stuff
        Div [
        ]
```

Renders nothing. I must configure something else but Main.fs is pretty empty too:

```
namespace FsharpTestSinglePageNext

type Global() =
    inherit System.Web.HttpApplication()

    member g.Application_Start(sender: obj, args: System.EventArgs) =
        ()
```

I do have index.html which gets rendered, but I want to render my HTML using the `Client.main`: 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>FsharpTestSinglePageNext</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="Content/FsharpTestSinglePageNext.css" />
    <script type="text/javascript" src="Content/FsharpTestSinglePageNext.head.js"></script>
</head>
<body>
    <div id="main">
       
    </div>
    <script type="text/javascript" src="Content/FsharpTestSinglePageNext.min.js"></script>
</body>
</html>
```

**Comment by granicz** [comment]
In this code, NOTHING inserts your DIV to any visible content.  You have a `Main` function that returns client-side markup, where are you calling it from?

**Comment by Ciantic** [comment]
Uhh. Is the running these lines: https://github.com/intellifactory/websharper.ui.next.samples/blob/master/src/Calculator.fs#L103-L105

**Comment by granicz** [comment]
No, it's the `let Sample = ...` lines in the bottom, which do a lot more than what you need.  If you look at the last line in the original template you are using, you should see:

        |> Doc.RunById "main"

This is responsible for adding whatever `Doc` value to the `main` placeholder in the master HTML file (from where the generated JS code is linked).

**Comment by Ciantic** [comment]
Thanks!

I emptied that and tried to copy & paste the examples, that was not a good idea since they weren't stand alone files.

This works

```
namespace FsharpUiNextSinglePageApp2

open WebSharper
open WebSharper.JavaScript
open WebSharper.JQuery
open WebSharper.UI.Next
open WebSharper.UI.Next.Notation
module H = WebSharper.UI.Next.Html

[<JavaScript>]
module Client =    
    let Main =
        (
            H.Div0 [
                Doc.TextNode "Hello World!"
            ]
        )
        |> Doc.RunById "main"
```

**Comment by granicz** [comment]
Cool.  Hopefully things will be more clear and simple copy-pasting will work better when we update this repository to use the latest syntax and simplify how samples are served and displayed.
