### ISSUE TITLE
Examples using plain HTML to create views?

### ISSUE THREAD

**Issue by fdcastel** [intellifactory/websharper.ui.next.samples#27]
What about to create some examples showing how to use plain html for the views?

Please, don't get me wrong. I understand the objective of WebSharper is to provide a first-class F# solution to web development. However, the idiom used for HTML generation via F# is a high cost barrier for newbies. Also, you know, sometimes there's no better tool for the job than plain old html :)

I would love to use WebSharper to drive some highly complicated html interfaces, but the cost to port them to F# is a no-go.

**Comment by granicz** [comment]
Have you seen the UI.Next HTML templates?  They give you exactly that - you can externalize some or all of your HTML markup into `.html` files.  They are used in the templates in the public installers, but they are largely undocumented in the repo, unfortunately.

**Comment by fdcastel** [comment]
Uhhh. Actually, no, I didn't ;) -- Thank you very much granicz! I'll look at it.

**Comment by fdcastel** [comment]
Following granicz tip and the [Docs](https://github.com/intellifactory/websharper.ui.next/blob/master/docs/Templates.md) (which I didn't see it yesterday... DOH! :) ) -- I added a sample similar to InputTransform using html for the view ( https://github.com/intellifactory/websharper.ui.next.samples/pull/25 )

Feel free to add it to the project, if you like. I think it could be very useful for newbies.
